export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_CLEAR = "FETCH_USER_CLEAR";
export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT";
